language: node_js
node_js:
  - "v10.15.0"

before_install:
  - sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

install:
  - npm install
  - pip install WeasyPrint

script:
  - hackmyresume build resume.json TO out/resume.all -p weasyprint -t positive
